// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71ApBY1kTMKB9Bs6Px5NxJ6IikoZYwG0',
    appId: '1:471063968269:web:89b70457c01150a7647344',
    messagingSenderId: '471063968269',
    projectId: 'basic-chat-emilio-pavel',
    authDomain: 'basic-chat-emilio-pavel.firebaseapp.com',
    storageBucket: 'basic-chat-emilio-pavel.firebasestorage.app',
    measurementId: 'G-D5MMG4MGS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9pPkLnk7rBPwS3VMraY5i9FUtqCVCGZY',
    appId: '1:471063968269:android:e8a239fed30d4acc647344',
    messagingSenderId: '471063968269',
    projectId: 'basic-chat-emilio-pavel',
    storageBucket: 'basic-chat-emilio-pavel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOV8MUByjcL8_Z6KbNObV-EMxERznw9c',
    appId: '1:471063968269:ios:c5c5dcf14b9fc73e647344',
    messagingSenderId: '471063968269',
    projectId: 'basic-chat-emilio-pavel',
    storageBucket: 'basic-chat-emilio-pavel.firebasestorage.app',
    iosBundleId: 'com.example.basicChatEmilioPavel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOV8MUByjcL8_Z6KbNObV-EMxERznw9c',
    appId: '1:471063968269:ios:c5c5dcf14b9fc73e647344',
    messagingSenderId: '471063968269',
    projectId: 'basic-chat-emilio-pavel',
    storageBucket: 'basic-chat-emilio-pavel.firebasestorage.app',
    iosBundleId: 'com.example.basicChatEmilioPavel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC71ApBY1kTMKB9Bs6Px5NxJ6IikoZYwG0',
    appId: '1:471063968269:web:b678831309d25e1b647344',
    messagingSenderId: '471063968269',
    projectId: 'basic-chat-emilio-pavel',
    authDomain: 'basic-chat-emilio-pavel.firebaseapp.com',
    storageBucket: 'basic-chat-emilio-pavel.firebasestorage.app',
    measurementId: 'G-Q1GGGBK2ER',
  );
}
